I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/story/chapter4.rpy", line 63, in script
    label conversations_refresh(name):
TypeError: Missing required positional arguments: 'name'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/story/chapter4.rpy", line 63, in script
    label conversations_refresh(name):
  File "C:\Users\alexs\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 1081, in execute
    values = apply_arguments(self.parameters, renpy.store._args, renpy.store._kwargs)
  File "C:\Users\alexs\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 296, in apply_arguments
    return parameters.apply(args, kwargs, ignore_errors)
  File "C:\Users\alexs\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 232, in apply
    raise TypeError(
TypeError: Missing required positional arguments: 'name'

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
WacBonalds 1.0
Thu Nov  2 15:25:11 2023
